- id: inifix-format
  name: Format .ini files
  language: python
  entry: inifix-format
  description: Format configuration files with inifix-format
  files: (\.ini)$
- id: inifix-validate
  name: Validate .ini files (no formatting)
  language: python
  entry: inifix-validate
  description: Validate configuration files with inifix-validate
  files: (\.ini)$
