ci:
    autofix_prs: true
    autoupdate_schedule: "monthly"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, main]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.19.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
